@localhost=localhost:4004/odata/v4/main
@id=b7dca0fd-d73f-49e0-91bc-b9b0583067d5
@customerId=713ba437-e869-42aa-b92b-bbc95763f80c
@productId=778fb29f-15df-49cc-b4eb-73d581fc743a

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 398,
    "items": [
        {
            "id": "778fb29f-15df-49cc-b4eb-73d581fc743a",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "e4225502-fb12-4da3-b098-789eac8c532b",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "teste"
}

###

# Buscar todos pedidos maiores ou iguais a 2 milhões
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 2000000
Content-Type: application/json

###

# Buscar todos pedidos menores ou iguais a 200k
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 200000
Content-Type: application/json

###

# Expandindo os items, produtos e customers
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product),customer
Content-Type: application/json

###

# Expandindo os items, produtos, customers e filtrando
GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity le 30),customer
Content-Type: application/json

###

# Selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=email)
Content-Type: application/json

###

# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json

###

# Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=0&$top=5
Content-Type: application/json